# Generated by Django 3.2.7 on 2021-09-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_control', '0002_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
